GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "VS code rest client",
  "important": true
}

###
DELETE http://localhost:3001/api/notes/65f86f10e836b454d2a4eb83

###
PUT http://localhost:3001/api/notes/65f86ebcce5203ce87eabe2d
Content-Type: application/json

{
  "content": "abbba",
  "important": true
}
